-- Insert para estoque
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(1, 17, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(2, 23, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(3, 30, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(4, 33, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());
INSERT INTO estoque (iLivro, nValor, iSituacaoEstoque, dtCadastro) VALUES(5, 40, 3, current_date());

-- Insert para pedido
INSERT INTO pedido (iUsuario, iFrete, sNumeroPedido, iEndereco, nTotal, dtCadastro) VALUES(2, 25,  '002_20190115152119_00001', 1, 291, '2019-01-15');
INSERT INTO pedido (iUsuario, iFrete, sNumeroPedido, iEndereco, nTotal, dtCadastro) VALUES(2, 25,  '002_20190215152119_00002', 1, 291, '2019-02-15');
INSERT INTO pedido (iUsuario, iFrete, sNumeroPedido, iEndereco, nTotal, dtCadastro) VALUES(2, 25,  '002_20190315152119_00003', 1, 291, '2019-03-15');
INSERT INTO pedido (iUsuario, iFrete, sNumeroPedido, iEndereco, nTotal, dtCadastro) VALUES(2, 25,  '002_20190415152119_00004', 1, 291, '2019-04-15');
INSERT INTO pedido (iUsuario, iFrete, sNumeroPedido, iEndereco, nTotal, dtCadastro) VALUES(2, 25,  '002_20190516152119_00005', 1, 291, '2019-05-15');
INSERT INTO pedido (iUsuario, iFrete, sNumeroPedido, iEndereco, nTotal, dtCadastro) VALUES(2, 25,  '002_20190615152119_00006', 1, 291, '2019-06-15');

-- Insert para itempedido
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(1, 1, 1,  1, 17, 1, '2019-01-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(1, 2, 1,  1, 17, 1, '2019-01-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(2, 3, 1,  1, 17, 1, '2019-02-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(2, 4, 1,  1, 17, 1, '2019-02-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(3, 5, 1,  1, 17, 1, '2019-03-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(3, 6, 1,  1, 17, 1, '2019-03-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(4, 7, 1,  1, 17, 1, '2019-04-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(4, 8, 1,  1, 17, 1, '2019-04-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(5, 9, 1,  1, 17, 1, '2019-05-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(5, 10, 1,  1, 17, 1, '2019-05-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 11, 1,  1, 17, 1, '2019-06-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 12, 1,  1, 17, 1, '2019-06-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(1, 13, 2,  1, 23, 1, '2019-01-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(1, 14, 2,  1, 23, 1, '2019-01-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(2, 15, 2,  1, 23, 1, '2019-02-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(2, 16, 2,  1, 23, 1, '2019-02-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(3, 17, 2,  1, 23, 1, '2019-03-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(3, 18, 2,  1, 23, 1, '2019-03-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(4, 19, 2,  1, 23, 1, '2019-04-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(4, 20, 2,  1, 23, 1, '2019-04-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(5, 21, 2,  1, 23, 1, '2019-05-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(5, 22, 2,  1, 23, 1, '2019-05-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 23, 2,  1, 23, 1, '2019-06-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 24, 2,  1, 23, 1, '2019-06-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(1, 25, 3,  1, 30, 1, '2019-01-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(1, 26, 3,  1, 30, 1, '2019-01-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(2, 27, 3,  1, 30, 1, '2019-02-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(2, 28, 3,  1, 30, 1, '2019-02-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(3, 29, 3,  1, 30, 1, '2019-03-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(3, 30, 3,  1, 30, 1, '2019-03-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(4, 31, 3,  1, 30, 1, '2019-04-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(4, 32, 3,  1, 30, 1, '2019-04-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(5, 33, 3,  1, 30, 1, '2019-05-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(5, 34, 3,  1, 30, 1, '2019-05-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 35, 3,  1, 30, 1, '2019-06-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 36, 3,  1, 30, 1, '2019-06-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(1, 37, 4,  1, 33, 1, '2019-01-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(1, 38, 4,  1, 33, 1, '2019-01-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(2, 39, 4,  1, 33, 1, '2019-02-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(2, 40, 4,  1, 33, 1, '2019-02-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(3, 41, 4,  1, 33, 1, '2019-03-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(3, 42, 4,  1, 33, 1, '2019-03-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(4, 43, 4,  1, 33, 1, '2019-04-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(4, 44, 4,  1, 33, 1, '2019-04-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(5, 45, 4,  1, 33, 1, '2019-05-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(5, 46, 4,  1, 33, 1, '2019-05-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 47, 4,  1, 33, 1, '2019-06-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 48, 4,  1, 33, 1, '2019-06-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(1, 49, 5,  1, 40, 1, '2019-01-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(1, 50, 5,  1, 40, 1, '2019-01-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(2, 51, 5,  1, 40, 1, '2019-02-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(2, 52, 5,  1, 40, 1, '2019-02-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(3, 53, 5,  1, 40, 1, '2019-03-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(3, 54, 5,  1, 40, 1, '2019-03-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(4, 55, 5,  1, 40, 1, '2019-04-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(4, 56, 5,  1, 40, 1, '2019-04-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(5, 57, 5,  1, 40, 1, '2019-05-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(5, 58, 5,  1, 40, 1, '2019-05-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 59, 5,  1, 40, 1, '2019-06-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 60, 5,  1, 40, 1, '2019-06-15');

INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(2, 61, 1,  1, 17, 1, '2019-02-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(2, 62, 1,  1, 17, 1, '2019-02-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(4, 63, 1,  1, 17, 1, '2019-04-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 64, 1,  1, 17, 1, '2019-06-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 65, 1,  1, 17, 1, '2019-06-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(1, 66, 2,  1, 23, 1, '2019-01-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(3, 67, 2,  1, 23, 1, '2019-03-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(3, 68, 2,  1, 23, 1, '2019-03-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(5, 69, 2,  1, 23, 1, '2019-05-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(5, 70, 2,  1, 23, 1, '2019-05-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(1, 71, 3,  1, 30, 1, '2019-01-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(2, 72, 3,  1, 30, 1, '2019-02-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(2, 73, 3,  1, 30, 1, '2019-02-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(2, 74, 3,  1, 30, 1, '2019-02-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(3, 75, 3,  1, 30, 1, '2019-03-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(1, 76, 4,  1, 33, 1, '2019-01-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(3, 77, 4,  1, 33, 1, '2019-03-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 78, 4,  1, 33, 1, '2019-06-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 79, 4,  1, 33, 1, '2019-06-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 80, 4,  1, 33, 1, '2019-06-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(4, 81, 5,  1, 40, 1, '2019-04-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(5, 82, 5,  1, 40, 1, '2019-05-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(5, 83, 5,  1, 40, 1, '2019-05-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 84, 5,  1, 40, 1, '2019-06-15');
INSERT INTO itempedido (iPedido, iEstoque, iLivro, nQtde, nValor, iSituacaoItem, dtCadastro) VALUES(6, 85, 5,  1, 40, 1, '2019-06-15');

-- Insert para formadepagamento
INSERT INTO formadepagamento (iPedido, iPagamento, nValor, iTipoPagamento, dtCadastro) VALUES(1,  '1', 191, 1, '2019-01-15');
INSERT INTO formadepagamento (iPedido, iPagamento, nValor, iTipoPagamento, dtCadastro) VALUES(1,  '2', 100, 1, '2019-01-15');
INSERT INTO formadepagamento (iPedido, iPagamento, nValor, iTipoPagamento, dtCadastro) VALUES(2,  '1', 191, 1, '2019-02-15');
INSERT INTO formadepagamento (iPedido, iPagamento, nValor, iTipoPagamento, dtCadastro) VALUES(2,  '2', 100, 1, '2019-02-15');
INSERT INTO formadepagamento (iPedido, iPagamento, nValor, iTipoPagamento, dtCadastro) VALUES(3,  '1', 191, 1, '2019-03-15');
INSERT INTO formadepagamento (iPedido, iPagamento, nValor, iTipoPagamento, dtCadastro) VALUES(3,  '2', 100, 1, '2019-03-15');
INSERT INTO formadepagamento (iPedido, iPagamento, nValor, iTipoPagamento, dtCadastro) VALUES(4,  '1', 191, 1, '2019-04-15');
INSERT INTO formadepagamento (iPedido, iPagamento, nValor, iTipoPagamento, dtCadastro) VALUES(4,  '2', 100, 1, '2019-04-15');
INSERT INTO formadepagamento (iPedido, iPagamento, nValor, iTipoPagamento, dtCadastro) VALUES(5,  '1', 191, 1, '2019-05-15');
INSERT INTO formadepagamento (iPedido, iPagamento, nValor, iTipoPagamento, dtCadastro) VALUES(5,  '2', 100, 1, '2019-05-15');
INSERT INTO formadepagamento (iPedido, iPagamento, nValor, iTipoPagamento, dtCadastro) VALUES(6,  '1', 191, 1, '2019-06-15');
INSERT INTO formadepagamento (iPedido, iPagamento, nValor, iTipoPagamento, dtCadastro) VALUES(6,  '2', 100, 1, '2019-06-15');
